import { test, expect } from "@playwright/test";
import { inspectPage } from "./crawl";
import { PLATFORM_ROUTES } from "./routes";
import { authFile } from "./accounts";

test.use({ storageState: authFile("platform") });

for (const path of PLATFORM_ROUTES) {
  test(`platform: ${path} loads cleanly`, async ({ page }) => {
    await inspectPage(page, path);
  });
}

test("platform: an org detail page loads cleanly", async ({ page }) => {
  await page.goto("/platform");
  // Org ids are regenerated by every `db:seed` run — follow the first row's
  // link rather than hardcoding one.
  const firstOrgLink = page.locator('a[href^="/platform/orgs/"]').first();
  await expect(firstOrgLink).toBeVisible();
  const href = await firstOrgLink.getAttribute("href");
  await inspectPage(page, href!);
});
